name: Semgrep
on:
  pull_request: {}
  push:
    branches:
      - master
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run Semgrep scan
        uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          # Never fail the build due to findings on pushes.
          # Instead, just collect findings for semgrep.dev/manage/findings
          #auditOn: push
          # Upload findings to GitHub Advanced Security Dashboard [step 1/2]
          generateSarif: "1"
      # Upload findings to GitHub Advanced Security Dashboard [step 2/2]
      # This step will fail unless GH Enterprise is enabled
      # Commenting these lines out for now
      #- name: Upload SARIF file for GitHub Advanced Security Dashboard
      #  uses: github/codeql-action/upload-sarif@v1
      #  with:
      #    sarif_file: semgrep.sarif
      #    if: always()
